stages:
  import_raw_data:
    cmd: python src/data/import_raw_data.py
    deps:
      - src/data/import_raw_data.py
    outs:
      - data/raw/raw.csv

  make_dataset:
    cmd: python src/data/make_dataset.py
    deps:
      - data/raw/raw.csv
      - src/data/make_dataset.py
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  scale_dataset:
    cmd: python src/data/scale_dataset.py
    deps:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - src/data/scale_dataset.py
    outs:
      - data/processed/X_train_scaled.csv
      - data/processed/X_test_scaled.csv

  gridsearch_xgb:
    cmd: python src/models/gridsearch_xgb.py
    deps:
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - src/models/gridsearch_xgb.py
    outs:
      - models/xgb_best_params.pkl

  train_model:
    cmd: python src/models/train_model.py
    deps:
      - data/processed/X_train_scaled.csv
      - data/processed/y_train.csv
      - models/xgb_best_params.pkl
      - src/models/train_model.py
    outs:
      - models/trained_model.joblib

  evaluate_model:
    cmd: python src/models/evaluate_model.py
    deps:
      - data/processed/X_test_scaled.csv
      - data/processed/y_test.csv
      - models/trained_model.joblib
      - src/models/evaluate_model.py
    outs:
      - data/predictions.csv
